# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3.9.1 # Should be a command that runs python3.6+

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: ./venv/bin/python -m pylint
        language: system
        types: [python]
        args: ["--errors-only"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
exclude: "alembic|update_bdd.py"
